export interface SecurityTestItem {
  id: number;
  idServicio: string;
  plataforma: string;
  servicioTecnologico: string;
  idPruebaSeguridad: string;
  evaluacionAsociada: string;
  categoria: string;
  nombrePrueba: string;
  resultadoPrueba: string;
  comentariosPrueba: string;
  clasificacion: string;
  nombreHallazgo: string;
  descripcionPrueba: string;
  singleTarget: string;
  comandoBulk: string;
  targetsFile: string;
  comandoSingle: string;
  filtroBurpHistory: string;
  filtroBurpSearch: string;
  burpSuiteFile: string;
  comandoBurpFile: string;
  snippetDeveloperConsole: string;
  evidencias: {
    imagen: string;
    nota: string;
    canvasState?: any[];
  }[];
  herramientaSugerida: string;
  herramientaIncluyePrueba: string;
  referencias: string;
  mitreTactica: string;
  mitreTecnica: string;
  mitreId: string;
  cwe: string;
  fqdn: string;
  ambiente: string;
  cvssScore: number;
  cvssVector: string;

  // Additional 62 Excel columns mapping fields
  folio2?: string;
  fechaDeteccion?: string;
  nombreActivoTecnologico?: string;
  servicioSeguridadAsociado?: string;
  tipoRevision?: string;
  activoObjetivoPruebaSeguridad?: string;
  nombrePruebaSeguridad?: string;
  descripcionPruebaSeguridad?: string;
  resultadoPrueba2?: string;
  evidenciaPrincipal?: string;
  notasPruebaSeguridad?: string;
  evidenciaComplementaria1?: string;
  evidenciaComplementaria2?: string;
  evidenciaComplementaria3?: string;
  descripcion?: string;
  amenaza?: string;
  recomendaciones?: string;
  poc?: string;
}

export const PRUEBAS_INITIAL: SecurityTestItem[] = [
  {
    id: 1,
    idServicio: 'EIM ID – 9847446 - SVC-DIGITAL-BANKING-US - COMET ID 152318',
    plataforma: 'NETWORK',
    servicioTecnologico: 'HTTP/HTTPS',
    idPruebaSeguridad: 'CROS-WSTG-WEB-01',
    evaluacionAsociada: 'CROS Web Application Security Testing (WSTG) v2.0.0',
    categoria: '01-Information_Gathering',
    nombrePrueba: 'Conduct Search Engine Discovery Reconnaissance for Information Leakage',
    resultadoPrueba: 'Out Of Scope',
    comentariosPrueba: '',
    clasificacion: '',
    nombreHallazgo: '',
    descripcionPrueba: 'Realizar descubrimiento en motores de búsqueda para identificar fugas de información.',
    singleTarget: '',
    comandoBulk: '',
    targetsFile: '',
    comandoSingle: '',
    filtroBurpHistory: '',
    filtroBurpSearch: '',
    burpSuiteFile: '',
    comandoBurpFile: '',
    snippetDeveloperConsole: '',
    evidencias: [],
    herramientaSugerida: '',
    herramientaIncluyePrueba: '',
    referencias: 'https://owasp.org/www-project-web-security-testing-guide/',
    mitreTactica: 'Reconnaissance',
    mitreTecnica: 'Search Open Website/Domains',
    mitreId: 'T1593',
    cwe: 'CWE-200',
    fqdn: 'digitalbanking.spectre.local',
    ambiente: 'Producción',
    cvssScore: 0,
    cvssVector: '',
    folio2: 'F-WSTG-01',
    fechaDeteccion: '2026-07-02',
    nombreActivoTecnologico: 'digitalbanking.spectre.local',
    servicioSeguridadAsociado: 'EIM ID – 9847446',
    tipoRevision: 'Web App Pentest',
    activoObjetivoPruebaSeguridad: 'digitalbanking.spectre.local',
    nombrePruebaSeguridad: 'WSTG-01 Search Engine Discovery',
    descripcionPruebaSeguridad: 'Revisión pasiva de motores de búsqueda.',
    resultadoPrueba2: 'Out Of Scope',
    evidenciaPrincipal: '',
    notasPruebaSeguridad: '',
    evidenciaComplementaria1: '',
    evidenciaComplementaria2: '',
    evidenciaComplementaria3: '',
    descripcion: 'Identificación de indexados en Google/Bing.',
    amenaza: 'Fuga de datos indexados',
    recomendaciones: 'Configurar robots.txt correctamente',
    poc: 'Query: site:digitalbanking.spectre.local',
  },
  {
    id: 2,
    idServicio: 'EIM ID – 9847446 - SVC-DIGITAL-BANKING-US - COMET ID 152318',
    plataforma: 'NETWORK',
    servicioTecnologico: 'HTTP/HTTPS',
    idPruebaSeguridad: 'CROS-WSTG-WEB-02',
    evaluacionAsociada: 'CROS Web Application Security Testing (WSTG) v2.0.0',
    categoria: '01-Information_Gathering',
    nombrePrueba: 'Enumerate Applications on Webserver',
    resultadoPrueba: 'Out Of Scope',
    comentariosPrueba: '',
    clasificacion: '',
    nombreHallazgo: '',
    descripcionPrueba: 'Enumerar las aplicaciones instaladas en el servidor web.',
    singleTarget: '',
    comandoBulk: '',
    targetsFile: '',
    comandoSingle: '',
    filtroBurpHistory: '',
    filtroBurpSearch: '',
    burpSuiteFile: '',
    comandoBurpFile: '',
    snippetDeveloperConsole: '',
    evidencias: [],
    herramientaSugerida: 'BurpSuite Active Scan',
    herramientaIncluyePrueba: '',
    referencias: 'https://owasp.org/www-project-web-security-testing-guide/',
    mitreTactica: 'Discovery',
    mitreTecnica: 'Software Discovery',
    mitreId: 'T1518',
    cwe: 'CWE-200',
    fqdn: 'digitalbanking.spectre.local',
    ambiente: 'Producción',
    cvssScore: 0,
    cvssVector: '',
    folio2: 'F-WSTG-02',
    fechaDeteccion: '2026-07-02',
    nombreActivoTecnologico: 'digitalbanking.spectre.local',
    servicioSeguridadAsociado: 'EIM ID – 9847446',
    tipoRevision: 'Web App Pentest',
    activoObjetivoPruebaSeguridad: 'digitalbanking.spectre.local',
    nombrePruebaSeguridad: 'WSTG-02 Enumerate Applications',
    descripcionPruebaSeguridad: 'Enumeración activa de vhosts y subdominios.',
    resultadoPrueba2: 'Out Of Scope',
    evidenciaPrincipal: '',
    notasPruebaSeguridad: '',
    evidenciaComplementaria1: '',
    evidenciaComplementaria2: '',
    evidenciaComplementaria3: '',
    descripcion: 'Identificación de múltiples apps alojadas en el host.',
    amenaza: 'Descubrimiento de endpoints ocultos',
    recomendaciones: 'Deshabilitar listados innecesarios',
    poc: 'Nmap virtual hosts scan',
  },
  {
    id: 3,
    idServicio: 'EIM ID – 9847446 - SVC-DIGITAL-BANKING-US - COMET ID 152318',
    plataforma: 'NETWORK',
    servicioTecnologico: 'HTTP/HTTPS',
    idPruebaSeguridad: 'CROS-WSTG-WEB-03',
    evaluacionAsociada: 'CROS Web Application Security Testing (WSTG) v2.0.0',
    categoria: '01-Information_Gathering',
    nombrePrueba: 'Fingerprint Web Application',
    resultadoPrueba: 'PASSED',
    comentariosPrueba: '',
    clasificacion: '',
    nombreHallazgo: '',
    descripcionPrueba: 'Identificar las huellas digitales y componentes de la aplicación web.',
    singleTarget: '',
    comandoBulk: `awk '\nBEGIN{IGNORECASE=1}\n{\n  line=$0\n  if (match(line, /^(server|x-powered-by|x-aspnet-version|x-generator|via|x-runtime|x-rails|x-application-context)[[:space:]]*:/)) {\n    header=substr(line, RSTART, RLENGTH)\n    while (match(line, /([A-Za-z0-9._+-]+\\/[0-9]+(\\.[0-9]+){1,3}([A-Za-z0-9._+-]+)?)|((OpenSSL|LibreSSL|BoringSSL|nginx|Apache|httpd|IIS|Tomcat|Jetty|JBoss|WildFly|WebLogic|WebSphere|Spring|Struts|Django|Rails|Laravel|Express|Kestrel|ASP\\.NET|PHP|Node\\.js|Python|Java|Go|Golang|WordPress|Drupal|Joomla)[[:space:]]*[0-9]+(\\.[0-9]+){1,3}([A-Za-z0-9._+-]+)?)/)) {\n      print NR ":" header " " substr(line, RSTART, RLENGTH)\n      line=substr(line, RSTART+RLENGTH)\n    }\n  }\n}' BurpItems.txt`,
    targetsFile: 'BurpItems.txt',
    comandoSingle: `grep -Eo '(version|ver|release|rev|revision|build|buildid|build-id)[[:space:]]*[:=][[:space:]]*["'"'"'"]?[vV]?[0-9]+(\\.[0-9]+){1,4}([._-]?(alpha|beta|rc|pre|preview|snapshot|final|sp)[._-]?[0-9]*)?([+._-][A-Za-z0-9._-]+)?["'"'"'"]?|[A-Za-z][A-Za-z0-9._+-]{1,40}[[:space:]]*[/[:space:]-]*[vV]?[0-9]+(\\.[0-9]+){1,4}([._-]?(alpha|beta|rc|pre|preview|snapshot|final|sp)[._-]?[0-9]*)?([+._-][A-Za-z0-9._-]+)?' BurpItems.txt | tr '[:upper:]' '[:lower:]' | sed -E 's/^[[:space:]]+|[[:space:]]+$//g; s/[[:space:]]+/ /g' | sort | uniq -c | sort -nr`,
    filtroBurpHistory: '',
    filtroBurpSearch: '',
    burpSuiteFile: 'BurpItems.txt',
    comandoBurpFile: '',
    snippetDeveloperConsole: '',
    evidencias: [],
    herramientaSugerida: '',
    herramientaIncluyePrueba: '',
    referencias: 'https://owasp.org/www-project-web-security-testing-guide/',
    mitreTactica: 'Discovery',
    mitreTecnica: 'System Information Discovery',
    mitreId: 'T1082',
    cwe: 'CWE-200',
    fqdn: 'digitalbanking.spectre.local',
    ambiente: 'Producción',
    cvssScore: 0,
    cvssVector: '',
    folio2: 'F-WSTG-03',
    fechaDeteccion: '2026-07-02',
    nombreActivoTecnologico: 'digitalbanking.spectre.local',
    servicioSeguridadAsociado: 'EIM ID – 9847446',
    tipoRevision: 'Web App Pentest',
    activoObjetivoPruebaSeguridad: 'digitalbanking.spectre.local',
    nombrePruebaSeguridad: 'WSTG-03 Fingerprint Web App',
    descripcionPruebaSeguridad: 'Fingerprint de componentes mediante cabeceras HTTP.',
    resultadoPrueba2: 'PASSED',
    evidenciaPrincipal: '',
    notasPruebaSeguridad: '',
    evidenciaComplementaria1: '',
    evidenciaComplementaria2: '',
    evidenciaComplementaria3: '',
    descripcion: 'Escaneo pasivo de cookies y tecnologías.',
    amenaza: 'Divulgación de versiones vulnerables',
    recomendaciones: 'Mitigar disclosure en respuestas',
    poc: 'Terminal script output check',
  },
  {
    id: 4,
    idServicio: 'EIM ID – 9847446 - SVC-DIGITAL-BANKING-US - COMET ID 152318',
    plataforma: 'NETWORK',
    servicioTecnologico: 'HTTP/HTTPS',
    idPruebaSeguridad: 'CROS-WSTG-WEB-04',
    evaluacionAsociada: 'CROS Web Application Security Testing (WSTG) v2.0.0',
    categoria: '01-Information_Gathering',
    nombrePrueba: 'Fingerprint Web Application Framework',
    resultadoPrueba: 'PASSED',
    comentariosPrueba: '',
    clasificacion: '',
    nombreHallazgo: '',
    descripcionPrueba: 'Identificar el framework web utilizado en la aplicación.',
    singleTarget: '',
    comandoBulk: '',
    targetsFile: 'BurpItems.txt',
    comandoSingle: `grep -Eo '(version|ver|release|rev|revision|build|buildid|build-id)[[:space:]]*[:=][[:space:]]*["'"'"'"]?[vV]?[0-9]+(\\.[0-9]+){1,4}([._-]?(alpha|beta|rc|pre|preview|snapshot|final|sp)[._-]?[0-9]*)?([+._-][A-Za-z0-9._-]+)?["'"'"'"]?|[A-Za-z][A-Za-z0-9._+-]{1,40}[[:space:]]*[/[:space:]-]*[vV]?[0-9]+(\\.[0-9]+){1,4}([._-]?(alpha|beta|rc|pre|preview|snapshot|final|sp)[._-]?[0-9]*)?([+._-][A-Za-z0-9._-]+)?' BurpItems.txt | tr '[:upper:]' '[:lower:]' | sed -E 's/^[[:space:]]+|[[:space:]]+$//g; s/[[:space:]]+/ /g' | sort | uniq -c | sort -nr`,
    filtroBurpHistory: 'return requestResponse.hasResponse() && requestResponse.response().headers().stream().anyMatch(h -> Set.of("server","x-powered-by","x-aspnet-version","x-generator","via","x-runtime").contains(h.name().toLowerCase(java.util.Locale.ROOT)));',
    filtroBurpSearch: '(?i)(?:\\r?\\n)(server|x-powered-by|x-aspnet-version|x-generator|via|x-runtime|x-cache)\\s*:\\s*[^\\r\\n]+',
    burpSuiteFile: 'BurpItems.txt',
    comandoBurpFile: '',
    snippetDeveloperConsole: 'var mimeType = requestResponse.mimeType();\n\nreturn mimeType != MimeType.CSS\n && mimeType != MimeType.IMAGE_UNKNOWN\n && mimeType != MimeType.IMAGE_JPEG\n && mimeType != MimeType.IMAGE_GIF\n && mimeType != MimeType.IMAGE_PNG\n && mimeType != MimeType.IMAGE_BMP\n && mimeType != MimeType.IMAGE_TIFF\n && requestResponse.contains("Bootstrap v4.5.2", false);',
    evidencias: [
      { imagen: 'CAP_20260622_203719.png', nota: 'Captura inicial' },
      { imagen: 'CAP_20260622_145545.png', nota: 'Captura bootstrap' },
      { imagen: 'CAP_20260623_105413.png', nota: 'Captura final' }
    ],
    herramientaSugerida: '',
    herramientaIncluyePrueba: '',
    referencias: 'https://owasp.org/www-project-web-security-testing-guide/',
    mitreTactica: 'Discovery',
    mitreTecnica: 'System Information Discovery',
    mitreId: 'T1082',
    cwe: 'CWE-200',
    fqdn: 'digitalbanking.spectre.local',
    ambiente: 'Producción',
    cvssScore: 0,
    cvssVector: '',
    folio2: 'F-WSTG-04',
    fechaDeteccion: '2026-07-02',
    nombreActivoTecnologico: 'digitalbanking.spectre.local',
    servicioSeguridadAsociado: 'EIM ID – 9847446',
    tipoRevision: 'Web App Pentest',
    activoObjetivoPruebaSeguridad: 'digitalbanking.spectre.local',
    nombrePruebaSeguridad: 'WSTG-04 Framework Fingerprint',
    descripcionPruebaSeguridad: 'Mapeo de Bootstrap, React o Angular.',
    resultadoPrueba2: 'PASSED',
    evidenciaPrincipal: 'CAP_20260622_203719.png',
    notasPruebaSeguridad: 'Bootstrap v4.5.2 detectado pasivamente.',
    evidenciaComplementaria1: 'CAP_20260622_145545.png',
    evidenciaComplementaria2: 'CAP_20260623_105413.png',
    evidenciaComplementaria3: '',
    descripcion: 'Identificación de frameworks y bibliotecas de UI.',
    amenaza: 'Ataques dirigidos a frameworks conocidos',
    recomendaciones: 'Ofuscar bibliotecas front-end',
    poc: 'Burp history analysis of static files',
  },
  {
    id: 5,
    idServicio: 'EIM ID – 9847446 - SVC-DIGITAL-BANKING-US - COMET ID 152318',
    plataforma: 'NETWORK',
    servicioTecnologico: 'HTTP/HTTPS',
    idPruebaSeguridad: 'CROS-WSTG-WEB-05',
    evaluacionAsociada: 'CROS Web Application Security Testing (WSTG) v2.0.0',
    categoria: '01-Information_Gathering',
    nombrePrueba: 'Fingerprint Web Server',
    resultadoPrueba: 'PASSED',
    comentariosPrueba: '',
    clasificacion: '',
    nombreHallazgo: '',
    descripcionPrueba: 'Identificar el servidor web mediante firmas y cabeceras.',
    singleTarget: '',
    comandoBulk: '',
    targetsFile: 'BurpItems.txt',
    comandoSingle: '',
    filtroBurpHistory: 'return requestResponse.hasResponse() && requestResponse.response().headers().stream().anyMatch(h -> java.util.Set.of("server","via","x-powered-by","x-aspnet-version","x-generator","x-runtime","x-served-by","x-varnish","x-cache","x-cache-hits","x-amz-cf-id","x-amz-cf-pop","x-edge-location","x-request-id").contains(h.name().toLowerCase(java.util.Locale.ROOT)));',
    filtroBurpSearch: '(?i)(?:\\r?\\n)(server|via|x-powered-by|x-aspnet-version|x-generator|x-runtime|x-served-by|x-varnish|x-cache|x-cache-hits|x-amz-cf-id|x-amz-cf-pop|x-edge-location|x-request-id)\\s*:\\s*[^\\r\\n]+',
    burpSuiteFile: '',
    comandoBurpFile: '',
    snippetDeveloperConsole: '',
    evidencias: [
      { imagen: 'CAP_20260622_204215.png', nota: 'Captura servidor' }
    ],
    herramientaSugerida: 'BurpSuite Active Scan',
    herramientaIncluyePrueba: '',
    referencias: 'https://owasp.org/www-project-web-security-testing-guide/',
    mitreTactica: 'Discovery',
    mitreTecnica: 'System Information Discovery',
    mitreId: 'T1082',
    cwe: 'CWE-200',
    fqdn: 'digitalbanking.spectre.local',
    ambiente: 'Producción',
    cvssScore: 0,
    cvssVector: '',
    folio2: 'F-WSTG-05',
    fechaDeteccion: '2026-07-02',
    nombreActivoTecnologico: 'digitalbanking.spectre.local',
    servicioSeguridadAsociado: 'EIM ID – 9847446',
    tipoRevision: 'Web App Pentest',
    activoObjetivoPruebaSeguridad: 'digitalbanking.spectre.local',
    nombrePruebaSeguridad: 'WSTG-05 Web Server Fingerprint',
    descripcionPruebaSeguridad: 'Mapeo de servidor web mediante cabeceras HTTP.',
    resultadoPrueba2: 'PASSED',
    evidenciaPrincipal: 'CAP_20260622_204215.png',
    notasPruebaSeguridad: 'Header Server: nginx expuesto.',
    evidenciaComplementaria1: '',
    evidenciaComplementaria2: '',
    evidenciaComplementaria3: '',
    descripcion: 'Revisión de firmas del software servidor.',
    amenaza: 'Ataques dirigidos a vulnerabilidades conocidas de nginx',
    recomendaciones: 'Eliminar Server header en nginx.conf',
    poc: 'curl -I http://digitalbanking.spectre.local',
  },
  {
    id: 6,
    idServicio: 'EIM ID – 9847446 - SVC-DIGITAL-BANKING-US - COMET ID 152318',
    plataforma: 'NETWORK',
    servicioTecnologico: 'HTTP/HTTPS',
    idPruebaSeguridad: 'CROS-WSTG-WEB-06',
    evaluacionAsociada: 'CROS Web Application Security Testing (WSTG) v2.0.0',
    categoria: '01-Information_Gathering',
    nombrePrueba: 'Identify Application Entry Points',
    resultadoPrueba: 'PASSED',
    comentariosPrueba: '',
    clasificacion: '',
    nombreHallazgo: '',
    descripcionPrueba: 'Identificar puntos de entrada y flujos de datos en la aplicación.',
    singleTarget: '',
    comandoBulk: '',
    targetsFile: '',
    comandoSingle: '',
    filtroBurpHistory: 'return requestResponse.request().isInScope() != null && (java.util.Set.of("post","put","patch","delete").contains(requestResponse.request().isInScope().method().toLowerCase(java.util.Locale.ROOT)) || requestResponse.request().isInScope().url().contains("?") || requestResponse.request().isInScope().hasHeader("Cookie") || (requestResponse.request().isInScope().body() != null && requestResponse.request().isInScope().body().length() > 0));',
    filtroBurpSearch: '(?ims)(?:^(?:POST|PUT|PATCH|DELETE)\\s+\\S+\\s+HTTP/\\d(?:\\.\\d)?\\s*$|^\\s*Cookie\\s*:\\s*[^\\r\\n]+|^(?:POST|PUT|PATCH|DELETE)\\s+\\S+\\s+HTTP/\\d(?:\\.\\d)?.*?\\r?\\n\\r?\\n[^ \\r\\n].*?=\\s*[^&\\r\\n]+)',
    burpSuiteFile: '',
    comandoBurpFile: '',
    snippetDeveloperConsole: '',
    evidencias: [],
    herramientaSugerida: 'BurpSuite Active Scan',
    herramientaIncluyePrueba: '',
    referencias: 'https://owasp.org/www-project-web-security-testing-guide/',
    mitreTactica: 'Discovery',
    mitreTecnica: 'Application Discovery',
    mitreId: 'T1018',
    cwe: 'CWE-200',
    fqdn: 'digitalbanking.spectre.local',
    ambiente: 'Producción',
    cvssScore: 0,
    cvssVector: '',
    folio2: 'F-WSTG-06',
    fechaDeteccion: '2026-07-02',
    nombreActivoTecnologico: 'digitalbanking.spectre.local',
    servicioSeguridadAsociado: 'EIM ID – 9847446',
    tipoRevision: 'Web App Pentest',
    activoObjetivoPruebaSeguridad: 'digitalbanking.spectre.local',
    nombrePruebaSeguridad: 'WSTG-06 Entry Points Identification',
    descripcionPruebaSeguridad: 'Mapeo de APIs, cookies y peticiones POST.',
    resultadoPrueba2: 'PASSED',
    evidenciaPrincipal: '',
    notasPruebaSeguridad: '',
    evidenciaComplementaria1: '',
    evidenciaComplementaria2: '',
    evidenciaComplementaria3: '',
    descripcion: 'Análisis de parámetros de entrada controlables por el usuario.',
    amenaza: 'Manipulación de parámetros web',
    recomendaciones: 'Sanitizar todas las entradas',
    poc: 'Burp Suite input spider parameters list',
  },
  {
    id: 7,
    idServicio: 'EIM ID – 9847446 - SVC-DIGITAL-BANKING-US - COMET ID 152318',
    plataforma: 'NETWORK',
    servicioTecnologico: 'HTTP/HTTPS',
    idPruebaSeguridad: 'CROS-WSTG-WEB-07',
    evaluacionAsociada: 'CROS Web Application Security Testing (WSTG) v2.0.0',
    categoria: '01-Information_Gathering',
    nombrePrueba: 'Map Application Architecture',
    resultadoPrueba: 'FAILED',
    comentariosPrueba: '',
    clasificacion: '04 Hallazgo Informativo',
    nombreHallazgo: 'Divulgación de Arquitectura de Aplicación',
    descripcionPrueba: 'Mapear la arquitectura de red y de la aplicación mediante cabeceras diagnósticas.',
    singleTarget: '',
    comandoBulk: '',
    targetsFile: '',
    comandoSingle: '',
    filtroBurpHistory: 'return requestResponse.hasResponse() && requestResponse.response().headers().stream().anyMatch(h -> java.util.Set.of("via","x-cache","x-amz-cf-id","x-amz-cf-pop","x-amz-cf-ray","cf-ray","x-served-by","x-cache-hits","x-varnish","x-fastly-request-id","x-akamai-transformed","x-azure-ref","x-edge-location").contains(h.name().toLowerCase(java.util.Locale.ROOT)));',
    filtroBurpSearch: '(?im)^(via|x-cache|x-amz-cf-id|x-amz-cf-pop|x-amz-cf-ray|cf-ray|x-served-by|x-cache-hits|x-varnish|x-fastly-request-id|x-akamai-transformed|x-azure-ref|x-edge-location)\\s*:\\s*[^\\r\\n]+',
    burpSuiteFile: '',
    comandoBurpFile: '',
    snippetDeveloperConsole: '',
    evidencias: [
      { imagen: 'CAP_20260622_210145.png', nota: 'Evidencia arquitectura' }
    ],
    herramientaSugerida: 'BurpSuite Active Scan',
    herramientaIncluyePrueba: '',
    referencias: 'https://owasp.org/www-project-web-security-testing-guide/',
    mitreTactica: 'Discovery',
    mitreTecnica: 'System Information Discovery',
    mitreId: 'T1082',
    cwe: 'CWE-200',
    fqdn: 'digitalbanking.spectre.local',
    ambiente: 'Producción',
    cvssScore: 2.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    folio2: 'F-WSTG-07',
    fechaDeteccion: '2026-07-02',
    nombreActivoTecnologico: 'digitalbanking.spectre.local',
    servicioSeguridadAsociado: 'EIM ID – 9847446',
    tipoRevision: 'Web App Pentest',
    activoObjetivoPruebaSeguridad: 'digitalbanking.spectre.local',
    nombrePruebaSeguridad: 'WSTG-07 Application Architecture Mapping',
    descripcionPruebaSeguridad: 'Mapeo de Load Balancers y proxys inverso mediante via headers.',
    resultadoPrueba2: 'FAILED',
    evidenciaPrincipal: 'CAP_20260622_210145.png',
    notasPruebaSeguridad: 'Cabecera Via expone proxy interno.',
    evidenciaComplementaria1: '',
    evidenciaComplementaria2: '',
    evidenciaComplementaria3: '',
    descripcion: 'Fuga de detalles de la infraestructura de red.',
    amenaza: 'Reconocimiento de red y topología interna',
    recomendaciones: 'Ofuscar y eliminar cabecera Via del balanceador',
    poc: 'Análisis de headers HTTP en respuestas CDN',
  },
  {
    id: 8,
    idServicio: 'EIM ID – 9847446 - SVC-DIGITAL-BANKING-US - COMET ID 152318',
    plataforma: 'NETWORK',
    servicioTecnologico: 'HTTP/HTTPS',
    idPruebaSeguridad: 'CROS-WSTG-WEB-08',
    evaluacionAsociada: 'CROS Web Application Security Testing (WSTG) v2.0.0',
    categoria: '01-Information_Gathering',
    nombrePrueba: 'Map Execution Paths Through Application',
    resultadoPrueba: 'PASSED',
    comentariosPrueba: '',
    clasificacion: '',
    nombreHallazgo: '',
    descripcionPrueba: 'Identificar rutas de ejecución y navegación en la aplicación.',
    singleTarget: '',
    comandoBulk: '',
    targetsFile: '',
    comandoSingle: '',
    filtroBurpHistory: '',
    filtroBurpSearch: '',
    burpSuiteFile: '',
    comandoBurpFile: '',
    snippetDeveloperConsole: '',
    evidencias: [],
    herramientaSugerida: '',
    herramientaIncluyePrueba: '',
    referencias: 'https://owasp.org/www-project-web-security-testing-guide/',
    mitreTactica: 'Discovery',
    mitreTecnica: 'Application Discovery',
    mitreId: 'T1018',
    cwe: 'CWE-200',
    fqdn: 'digitalbanking.spectre.local',
    ambiente: 'Producción',
    cvssScore: 0,
    cvssVector: '',
    folio2: 'F-WSTG-08',
    fechaDeteccion: '2026-07-02',
    nombreActivoTecnologico: 'digitalbanking.spectre.local',
    servicioSeguridadAsociado: 'EIM ID – 9847446',
    tipoRevision: 'Web App Pentest',
    activoObjetivoPruebaSeguridad: 'digitalbanking.spectre.local',
    nombrePruebaSeguridad: 'WSTG-08 Execution Paths Mapping',
    descripcionPruebaSeguridad: 'Mapeo de rutas de código y redirecciones.',
    resultadoPrueba2: 'PASSED',
    evidenciaPrincipal: '',
    notasPruebaSeguridad: '',
    evidenciaComplementaria1: '',
    evidenciaComplementaria2: '',
    evidenciaComplementaria3: '',
    descripcion: 'Auditoría de flujos lógicos de navegación.',
    amenaza: 'Salto de controles lógicos de paso',
    recomendaciones: 'Validar rutas en lado servidor',
    poc: 'Site crawling and parameter mapping',
  },
  {
    id: 9,
    idServicio: 'EIM ID – 9847446 - SVC-DIGITAL-BANKING-US - COMET ID 152318',
    plataforma: 'NETWORK',
    servicioTecnologico: 'HTTP/HTTPS',
    idPruebaSeguridad: 'CROS-WSTG-WEB-09',
    evaluacionAsociada: 'CROS Web Application Security Testing (WSTG) v2.0.0',
    categoria: '01-Information_Gathering',
    nombrePrueba: 'Review Web Page Content for Information Leakage',
    resultadoPrueba: 'PASSED',
    comentariosPrueba: '',
    clasificacion: '',
    nombreHallazgo: '',
    descripcionPrueba: 'Revisar código fuente HTML/JS de las páginas web en busca de fugas de llaves API u otros datos sensibles.',
    singleTarget: '',
    comandoBulk: '',
    targetsFile: '',
    comandoSingle: '',
    filtroBurpHistory: 'return requestResponse.hasResponse() && requestResponse.response().body() != null && requestResponse.response().body().length() > 0 && java.util.regex.Pattern.compile("(?is)(<!--.*?-->|<meta\\\\b[^>]*(?:name|http-equiv)\\s*=\\s*[\'\\\\\\\"]?(?:author|generator|refresh|robots|keywords)[\'\\\\\\\"]?[^>]*>|<script\\\\b[^>]*>.*?</script>|sourceMappingURL\\\\s*=|\\\\.js\\\\.map\\\\b|AIza[0-9A-Za-z\\\\-_]{35}|\\\\b(?:AKIA|ASIA)[0-9A-Z]{16}\\\\b|\\\\b(?:10\\\\.|192\\\\.168\\\\.|172\\\\.(?:1[6-9]|2\\\\d|3[0-1])\\\\.)\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3}\\\\b|\\\\b(?:password|passwd|pwd|secret|api[_-]?key|token)\\\\b\\\\s*[:=])").matcher(requestResponse.response().body().toString()).find();',
    filtroBurpSearch: '(?is)(<!--.*?-->|<meta\\b[^>]*(?:name|http-equiv)\\s*=\\s*[\'"]?(?:author|generator|refresh|robots|keywords)[\'"]?[^>]*>|<script\\b[^>]*>.*?</script>|sourceMappingURL\\s*=|\\.js\\.map\\b|AIza[0-9A-Za-z\\-_]{35}|\\b(?:AKIA|ASIA)[0-9A-Z]{16}\\b|\\b(?:10\\.|192\\.168\\.|172\\.(?:1[6-9]|2\\d|3[0-1])\\.)\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b|\\b(?:password|passwd|pwd|secret|api[_-]?key|token)\\b\\s*[:=])',
    burpSuiteFile: '',
    comandoBurpFile: '',
    snippetDeveloperConsole: '',
    evidencias: [
      { imagen: 'CAP_20260622_211956.png', nota: 'Búsqueda de API keys' }
    ],
    herramientaSugerida: 'BurpSuite Active Scan',
    herramientaIncluyePrueba: '',
    referencias: 'https://owasp.org/www-project-web-security-testing-guide/',
    mitreTactica: 'Credential Access',
    mitreTecnica: 'Credentials in Files',
    mitreId: 'T1552',
    cwe: 'CWE-200',
    fqdn: 'digitalbanking.spectre.local',
    ambiente: 'Producción',
    cvssScore: 0,
    cvssVector: '',
    folio2: 'F-WSTG-09',
    fechaDeteccion: '2026-07-02',
    nombreActivoTecnologico: 'digitalbanking.spectre.local',
    servicioSeguridadAsociado: 'EIM ID – 9847446',
    tipoRevision: 'Web App Pentest',
    activoObjetivoPruebaSeguridad: 'digitalbanking.spectre.local',
    nombrePruebaSeguridad: 'WSTG-09 Information Leakage Content Review',
    descripcionPruebaSeguridad: 'Búsqueda de comentarios de depuración y llaves API en scripts JS.',
    resultadoPrueba2: 'PASSED',
    evidenciaPrincipal: 'CAP_20260622_211956.png',
    notasPruebaSeguridad: 'Búsqueda de credenciales y API keys.',
    evidenciaComplementaria1: '',
    evidenciaComplementaria2: '',
    evidenciaComplementaria3: '',
    descripcion: 'Análisis de fugas de datos en código cliente.',
    amenaza: 'Compromiso de llaves de API externas',
    recomendaciones: 'Remover source maps en producción y minimizar JS',
    poc: 'Regex search on developer tools console',
  },
  {
    id: 10,
    idServicio: 'EIM ID – 9847446 - SVC-DIGITAL-BANKING-US - COMET ID 152318',
    plataforma: 'NETWORK',
    servicioTecnologico: 'HTTP/HTTPS',
    idPruebaSeguridad: 'CROS-WSTG-WEB-10',
    evaluacionAsociada: 'CROS Web Application Security Testing (WSTG) v2.0.0',
    categoria: '01-Information_Gathering',
    nombrePrueba: 'Review Webserver Metafiles for Information Leakage',
    resultadoPrueba: 'PASSED',
    comentariosPrueba: '',
    clasificacion: '',
    nombreHallazgo: '',
    descripcionPrueba: 'Analizar metafiles (robots.txt, security.txt, sitemap.xml) buscando directorios ocultos.',
    singleTarget: '',
    comandoBulk: '',
    targetsFile: '',
    comandoSingle: '',
    filtroBurpHistory: 'return requestResponse.request().isInScope() != null && java.util.regex.Pattern.compile("(?i)(?:^|/)(?:robots\\\\.txt|sitemap(?:_index)?\\\\.xml|sitemap\\.xml\\.gz|security\\.txt|humans\\.txt)(?:$|[?#])|(?:^|/)\\\\.well-known/security\\\\.txt(?:$|[?#])").matcher(requestResponse.request().isInScope().url()).find();',
    filtroBurpSearch: '',
    burpSuiteFile: '',
    comandoBurpFile: '',
    snippetDeveloperConsole: '',
    evidencias: [],
    herramientaSugerida: 'BurpSuite Active Scan',
    herramientaIncluyePrueba: '',
    referencias: 'https://owasp.org/www-project-web-security-testing-guide/',
    mitreTactica: 'Discovery',
    mitreTecnica: 'Software Discovery',
    mitreId: 'T1518',
    cwe: 'CWE-200',
    fqdn: 'digitalbanking.spectre.local',
    ambiente: 'Producción',
    cvssScore: 0,
    cvssVector: '',
    folio2: 'F-WSTG-10',
    fechaDeteccion: '2026-07-02',
    nombreActivoTecnologico: 'digitalbanking.spectre.local',
    servicioSeguridadAsociado: 'EIM ID – 9847446',
    tipoRevision: 'Web App Pentest',
    activoObjetivoPruebaSeguridad: 'digitalbanking.spectre.local',
    nombrePruebaSeguridad: 'WSTG-10 Metafiles Review',
    descripcionPruebaSeguridad: 'Revisión de robots.txt y sitemap.xml.',
    resultadoPrueba2: 'PASSED',
    evidenciaPrincipal: '',
    notasPruebaSeguridad: '',
    evidenciaComplementaria1: '',
    evidenciaComplementaria2: '',
    evidenciaComplementaria3: '',
    descripcion: 'Análisis de archivos de configuración indexables.',
    amenaza: 'Exposición de rutas de administración',
    recomendaciones: 'Remover rutas administrativas de robots.txt',
    poc: 'Checking domain/robots.txt endpoint',
  }
];
