export interface EvaluacionItem {
  id: number;
  folio: string;
  servicio: string;
  tipo: string;
  enAlcance: boolean;
  fase: string;
  subFase: string;
  aplicabilidad: string;
  actividad: string;
  completado: boolean;
  descripcion: string;
}

export const EVALUACIONES_INITIAL: EvaluacionItem[] = [
  // ==========================================
  // PTECN - INFRAESTRUCTURA (35 items)
  // ==========================================
  {
    id: 1,
    folio: 'PTECN-INF-EVAL-01',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Netdiscover',
    completado: false,
    descripcion: 'Descubrimiento pasivo y activo de direcciones IP en la red local utilizando peticiones ARP.',
  },
  {
    id: 2,
    folio: 'PTECN-INF-EVAL-02',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'SNMP Walk',
    completado: false,
    descripcion: 'Consulta masiva de OIDs de SNMP para extraer información de configuración y usuarios en equipos activos.',
  },
  {
    id: 3,
    folio: 'PTECN-INF-EVAL-03',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'SMB Enumeration',
    completado: false,
    descripcion: 'Identificación de recursos compartidos (shares), políticas de contraseña y enumeración de usuarios vía protocolos SMB/CIFS.',
  },
  {
    id: 4,
    folio: 'PTECN-INF-EVAL-04',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'LDAP Search',
    completado: false,
    descripcion: 'Consulta de directorios activos mediante LDAP para enumerar objetos, grupos de seguridad y configuraciones.',
  },
  {
    id: 5,
    folio: 'PTECN-INF-EVAL-05',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'RPCinfo',
    completado: false,
    descripcion: 'Mapeo de puertos asociados al servicio RPC Bind para identificar servicios y demonios activos.',
  },
  {
    id: 6,
    folio: 'PTECN-INF-EVAL-06',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Fingerprinting OS',
    completado: false,
    descripcion: 'Identificación remota de sistemas operativos y parches a través del análisis de la pila TCP/IP.',
  },
  {
    id: 7,
    folio: 'PTECN-INF-EVAL-07',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'SMTP User Recon',
    completado: false,
    descripcion: 'Verificación y enumeración de cuentas de correo válidas usando comandos VRFY/EXPN sobre SMTP.',
  },
  {
    id: 8,
    folio: 'PTECN-INF-EVAL-08',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis Automatizado',
    aplicabilidad: 'Obligatorio',
    actividad: 'OpenVAS',
    completado: false,
    descripcion: 'Escaneo automatizado de vulnerabilidades de red utilizando el motor de OpenVAS / Greenbone.',
  },
  {
    id: 9,
    folio: 'PTECN-INF-EVAL-09',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis Específico',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nuclei',
    completado: false,
    descripcion: 'Escaneo basado en plantillas YAML personalizadas para detectar vulnerabilidades específicas en servicios.',
  },
  {
    id: 10,
    folio: 'PTECN-INF-EVAL-10',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Red',
    aplicabilidad: 'Obligatorio',
    actividad: 'Responder',
    completado: false,
    descripcion: 'Análisis pasivo y envenenamiento de peticiones NetBIOS (NBT-NS), LLMNR y MDNS en el segmento de red.',
  },
  {
    id: 11,
    folio: 'PTECN-INF-EVAL-11',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Pruebas manuales',
    aplicabilidad: 'Obligatorio',
    actividad: 'ORBIT Testing',
    completado: false,
    descripcion: 'Orbital Risk-Based Technical Testing en puertos y servicios específicos identificados.',
  },
  {
    id: 12,
    folio: 'PTECN-INF-EVAL-12',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Red',
    aplicabilidad: 'Obligatorio',
    actividad: 'Wireshark Analysis',
    completado: false,
    descripcion: 'Captura y análisis de paquetes de red para detectar fuga de credenciales o protocolos en texto plano.',
  },
  {
    id: 13,
    folio: 'PTECN-INF-EVAL-13',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Infraestructura',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nessus (Credentialed)',
    completado: false,
    descripcion: 'Auditoría interna profunda en sistemas con credenciales para detectar faltas de parches y configuraciones deficientes.',
  },
  {
    id: 14,
    folio: 'PTECN-INF-EVAL-14',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Host',
    aplicabilidad: 'Obligatorio',
    actividad: 'Lynis',
    completado: false,
    descripcion: 'Auditoría y endurecimiento (hardening) automático de sistemas basados en Unix/Linux.',
  },
  {
    id: 15,
    folio: 'PTECN-INF-EVAL-15',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Contenedores',
    aplicabilidad: 'Obligatorio',
    actividad: 'Trivy',
    completado: false,
    descripcion: 'Búsqueda de vulnerabilidades en imágenes de contenedores, sistemas de archivos locales y repositorios Git.',
  },
  {
    id: 16,
    folio: 'PTECN-INF-EVAL-16',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Versión',
    aplicabilidad: 'Obligatorio',
    actividad: 'Searchsploit',
    completado: false,
    descripcion: 'Búsqueda en la base de datos de Exploit-DB para identificar exploits públicos utilizables.',
  },
  {
    id: 17,
    folio: 'PTECN-INF-EVAL-17',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Fuerza Bruta',
    aplicabilidad: 'Obligatorio',
    actividad: 'Hydra',
    completado: false,
    descripcion: 'Ataques activos de adivinación de contraseñas por diccionario en múltiples protocolos de red.',
  },
  {
    id: 18,
    folio: 'PTECN-INF-EVAL-18',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Fuerza Bruta',
    aplicabilidad: 'Obligatorio',
    actividad: 'Medusa',
    completado: false,
    descripcion: 'Intentos paralelos de fuerza bruta contra servicios de login remoto con enfoque de alta velocidad.',
  },
  {
    id: 19,
    folio: 'PTECN-INF-EVAL-19',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Inyección de Comandos',
    aplicabilidad: 'Obligatorio',
    actividad: 'Manual Exploitation',
    completado: false,
    descripcion: 'Explotación manual de vulnerabilidades de inyección de comandos o control lógico.',
  },
  {
    id: 20,
    folio: 'PTECN-INF-EVAL-20',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Validación Técnica',
    aplicabilidad: 'Obligatorio',
    actividad: 'Metasploit Framework',
    completado: false,
    descripcion: 'Uso de módulos oficiales y personalizados para validar la explotabilidad real de fallas detectadas.',
  },
  {
    id: 21,
    folio: 'PTECN-INF-EVAL-21',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Acceso Forzado',
    aplicabilidad: 'Obligatorio',
    actividad: 'Patator',
    completado: false,
    descripcion: 'Pruebas de fuerza bruta y denegación de servicios lógicos usando la herramienta modular Patator.',
  },
  {
    id: 22,
    folio: 'PTECN-INF-EVAL-22',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Movimiento Lateral',
    aplicabilidad: 'Obligatorio',
    actividad: 'CrackMapExec',
    completado: false,
    descripcion: 'Evaluación y explotación automática del protocolo de autenticación en entornos Active Directory.',
  },
  {
    id: 23,
    folio: 'PTECN-INF-EVAL-23',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Movimiento Lateral',
    aplicabilidad: 'Obligatorio',
    actividad: 'Mimikatz',
    completado: false,
    descripcion: 'Extracción de contraseñas en texto plano, hashes NTLM y tickets Kerberos de la memoria LSASS.',
  },
  {
    id: 24,
    folio: 'PTECN-INF-EVAL-24',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Movimiento Lateral',
    aplicabilidad: 'Obligatorio',
    actividad: 'Impacket',
    completado: false,
    descripcion: 'Ejecución de scripts de control lateral, tales como psexec, wmiexec o smbexec para control remoto.',
  },
  {
    id: 25,
    folio: 'PTECN-INF-EVAL-25',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Password Cracking',
    aplicabilidad: 'Obligatorio',
    actividad: 'John the Ripper',
    completado: false,
    descripcion: 'Ataque de crackeo de hashes de contraseñas fuera de línea (offline) en entornos multihilo.',
  },
  {
    id: 26,
    folio: 'PTECN-INF-EVAL-26',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Password Cracking',
    aplicabilidad: 'Obligatorio',
    actividad: 'Hashcat',
    completado: false,
    descripcion: 'Crackeo rápido de hashes complejos asistido por aceleración gráfica de GPU.',
  },
  {
    id: 27,
    folio: 'PTECN-INF-EVAL-27',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Escalada de Privilegios',
    aplicabilidad: 'Obligatorio',
    actividad: 'BeRoot',
    completado: false,
    descripcion: 'Identificación de malas configuraciones comunes en sistemas Windows/Linux para elevar privilegios.',
  },
  {
    id: 28,
    folio: 'PTECN-INF-EVAL-28',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Escalada de Privilegios',
    aplicabilidad: 'Obligatorio',
    actividad: 'GTFOBins',
    completado: false,
    descripcion: 'Explotación de binarios del sistema Unix con permisos SUID mal configurados.',
  },
  {
    id: 29,
    folio: 'PTECN-INF-EVAL-29',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Ataques de Red',
    aplicabilidad: 'Obligatorio',
    actividad: 'Responder Poisoning',
    completado: false,
    descripcion: 'Captura de hashes NetNTLMv1/v2 forzando autenticación local falsificando servicios.',
  },
  {
    id: 30,
    folio: 'PTECN-INF-EVAL-30',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Evasión de Defensas',
    aplicabilidad: 'Obligatorio',
    actividad: 'Veil Framework',
    completado: false,
    descripcion: 'Generación de payloads y binarios indetectables por soluciones antivirus comunes (Bypass AV).',
  },
  {
    id: 31,
    folio: 'PTECN-INF-EVAL-31',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Exfiltración de Datos',
    aplicabilidad: 'Obligatorio',
    actividad: 'DNS Exfiltration',
    completado: false,
    descripcion: 'Canalización de información sensible a través de consultas y registros DNS alternativos.',
  },
  {
    id: 32,
    folio: 'PTECN-INF-EVAL-32',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Exfiltración de Datos',
    aplicabilidad: 'Obligatorio',
    actividad: 'ICMP Tunneling',
    completado: false,
    descripcion: 'Encapsulado de tráfico y datos de comando y control usando tramas de ping (ICMP).',
  },
  {
    id: 33,
    folio: 'PTECN-INF-EVAL-33',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Persistencia',
    aplicabilidad: 'Obligatorio',
    actividad: 'Netcat / Socat',
    completado: false,
    descripcion: 'Establecimiento de backdoors y shells reversas interactivas en puertos no supervisados.',
  },
  {
    id: 34,
    folio: 'PTECN-INF-EVAL-34',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Persistencia',
    aplicabilidad: 'Obligatorio',
    actividad: 'Metasploit Persistence',
    completado: false,
    descripcion: 'Instalación de servicios de persistencia automática en el sistema de archivos del host comprometido.',
  },
  {
    id: 35,
    folio: 'PTECN-INF-EVAL-35',
    servicio: 'PTECN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Evasión',
    aplicabilidad: 'Obligatorio',
    actividad: 'ProxyChains',
    completado: false,
    descripcion: 'Enrutamiento del tráfico de escaneo ofensivo a través de múltiples proxies SOCKS para anonimato.',
  },

  // ==========================================
  // PTECN - WEB & WEB API (39 items)
  // ==========================================
  {
    id: 36,
    folio: 'PTECN-WEB-EVAL-01',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Wappalyzer',
    completado: false,
    descripcion: 'Identificación pasiva de frameworks frontend, servidores web y librerías en la aplicación objetivo.',
  },
  {
    id: 37,
    folio: 'PTECN-WEB-EVAL-02',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Whatweb',
    completado: false,
    descripcion: 'Análisis detallado de tecnologías e infraestructura web mediante firmas del servidor y cookies.',
  },
  {
    id: 38,
    folio: 'PTECN-WEB-EVAL-03',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'dirb',
    completado: false,
    descripcion: 'Búsqueda sistemática de contenidos web no expuestos basados en wordlists estándar.',
  },
  {
    id: 39,
    folio: 'PTECN-WEB-EVAL-04',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Opcional',
    actividad: 'ffuf',
    completado: false,
    descripcion: 'Fuzzing web extremadamente veloz para el descubrimiento de recursos web, endpoints y vhosts.',
  },
  {
    id: 40,
    folio: 'PTECN-WEB-EVAL-05',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Burp Suite (Manual)',
    completado: false,
    descripcion: 'Intercepción de tráfico HTTP/HTTPS y análisis manual de peticiones en busca de parámetros inyectables.',
  },
  {
    id: 41,
    folio: 'PTECN-WEB-EVAL-06',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Burp Suite (Spider) Scan',
    completado: false,
    descripcion: 'Rastreo automático de enlaces y directorios para mapear por completo la superficie de la aplicación.',
  },
  {
    id: 42,
    folio: 'PTECN-WEB-EVAL-07',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Alternativo',
    actividad: 'Virtual Host Scan',
    completado: false,
    descripcion: 'Enumeración de subdominios y vhosts apuntando a la misma dirección IP del servidor web.',
  },
  {
    id: 43,
    folio: 'PTECN-WEB-EVAL-08',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'WordPress Scan',
    completado: false,
    descripcion: 'Escaneo específico contra instancias WordPress para listar plugins, temas vulnerables y usuarios.',
  },
  {
    id: 44,
    folio: 'PTECN-WEB-EVAL-09',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis Web (DAST)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Acunetix Scan',
    completado: false,
    descripcion: 'Análisis DAST automatizado para detectar vulnerabilidades críticas como XSS, SQLi, SSRF y configuraciones deficientes.',
  },
  {
    id: 45,
    folio: 'PTECN-WEB-EVAL-10',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis Web (DAST)',
    aplicabilidad: 'Opcional',
    actividad: 'Zaproxy Scan',
    completado: false,
    descripcion: 'Uso del escáner dinámico OWASP ZAP para auditorías rápidas automatizadas.',
  },
  {
    id: 46,
    folio: 'PTECN-WEB-EVAL-11',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Cifrado',
    aplicabilidad: 'Obligatorio',
    actividad: 'sslscan',
    completado: false,
    descripcion: 'Determinación de los cifrados, protocolos TLS/SSL soportados y vulnerabilidades en la configuración criptográfica.',
  },
  {
    id: 47,
    folio: 'PTECN-WEB-EVAL-12',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Cifrado',
    aplicabilidad: 'Opcional',
    actividad: 'openssl (s_client)',
    completado: false,
    descripcion: 'Conexión manual a puertos HTTPS para validar certificados, TLS Handshakes y vulnerabilidades de negociación.',
  },
  {
    id: 48,
    folio: 'PTECN-WEB-EVAL-13',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Cifrado',
    aplicabilidad: 'Opcional',
    actividad: 'tlssled',
    completado: false,
    descripcion: 'Script de línea de comandos para evaluar la seguridad de la capa SSL/TLS del host web.',
  },
  {
    id: 49,
    folio: 'PTECN-WEB-EVAL-14',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Cifrado',
    aplicabilidad: 'Opcional',
    actividad: 'TestSSL.sh',
    completado: false,
    descripcion: 'Pruebas extensivas en puertos criptográficos para evaluar ciphers débiles, Logjam, Heartbleed y POODLE.',
  },
  {
    id: 50,
    folio: 'PTECN-WEB-EVAL-15',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Cifrado',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nmap (HTTP y SSL Scripts)',
    completado: false,
    descripcion: 'Ejecución de scripts del NSE para diagnosticar vulnerabilidades en la suite criptográfica del servidor.',
  },
  {
    id: 51,
    folio: 'PTECN-WEB-EVAL-16',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis Específico',
    aplicabilidad: 'Opcional',
    actividad: 'Nikto',
    completado: false,
    descripcion: 'Escáner clásico de servidores web que reporta archivos peligrosos, configuraciones obsoletas y cookies inseguras.',
  },
  {
    id: 52,
    folio: 'PTECN-WEB-EVAL-17',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Pruebas híbridas',
    aplicabilidad: 'Obligatorio',
    actividad: 'OWASP WSTG Testing',
    completado: false,
    descripcion: 'Metodología integral para realizar pruebas ofensivas completas bajo el framework de pruebas WSTG.',
  },
  {
    id: 53,
    folio: 'PTECN-WEB-EVAL-18',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Pruebas manuales',
    aplicabilidad: 'Obligatorio',
    actividad: 'ORBOWAT Testing',
    completado: false,
    descripcion: 'Análisis ofensivo manual y auditoría especializada de lógica en backend web.',
  },
  {
    id: 54,
    folio: 'PTECN-WEB-EVAL-19',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Seguridad de Transporte',
    aplicabilidad: 'Obligatorio',
    actividad: 'Cookies Verification',
    completado: false,
    descripcion: 'Verificación de flags de seguridad en cookies de sesión (Secure, HttpOnly, SameSite).',
  },
  {
    id: 55,
    folio: 'PTECN-WEB-EVAL-20',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Seguridad de Transporte',
    aplicabilidad: 'Obligatorio',
    actividad: 'Headers Verification',
    completado: false,
    descripcion: 'Auditoría de cabeceras de protección (HSTS, CSP, X-Frame-Options, X-Content-Type-Options).',
  },
  {
    id: 56,
    folio: 'PTECN-WEB-EVAL-21',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Sesión',
    aplicabilidad: 'Opcional',
    actividad: 'Burp Cookie Analysis',
    completado: false,
    descripcion: 'Análisis estadístico de la entropía y predictibilidad de las cookies de sesión con Burp Sequencer.',
  },
  {
    id: 57,
    folio: 'PTECN-WEB-EVAL-22',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de CORS',
    aplicabilidad: 'Opcional',
    actividad: 'Corsy',
    completado: false,
    descripcion: 'Identificación de debilidades y malas configuraciones en las políticas de CORS (Cross-Origin Resource Sharing).',
  },
  {
    id: 58,
    folio: 'PTECN-WEB-EVAL-23',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Cabeceras',
    aplicabilidad: 'Opcional',
    actividad: 'SecurityHeaders.io',
    completado: false,
    descripcion: 'Calificación automática de la postura de seguridad de la infraestructura a través de cabeceras de respuesta.',
  },
  {
    id: 59,
    folio: 'PTECN-WEB-EVAL-24',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Inyección de Datos',
    aplicabilidad: 'Opcional',
    actividad: 'SQLmap',
    completado: false,
    descripcion: 'Automatización del proceso de detección y explotación de inyecciones de código SQL (SQLi).',
  },
  {
    id: 60,
    folio: 'PTECN-WEB-EVAL-25',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Pruebas de Aplicación',
    aplicabilidad: 'Opcional',
    actividad: 'Burp Suite Pro',
    completado: false,
    descripcion: 'Escaneo avanzado y ataques personalizados con módulos Intruder y Repeater de Burp Suite.',
  },
  {
    id: 61,
    folio: 'PTECN-WEB-EVAL-26',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Explotación de BD',
    aplicabilidad: 'Opcional',
    actividad: 'NoSQLMap',
    completado: false,
    descripcion: 'Explotación manual y automática de inyecciones en base de datos orientadas a documentos (NoSQL).',
  },
  {
    id: 62,
    folio: 'PTECN-WEB-EVAL-27',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Manipulación de Datos',
    aplicabilidad: 'Opcional',
    actividad: 'CyberChef',
    completado: false,
    descripcion: 'Decodificación y manipulación de strings en bases numéricas, hash y esquemas de cifrado.',
  },
  {
    id: 63,
    folio: 'PTECN-WEB-EVAL-28',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Ataque de Login',
    aplicabilidad: 'Opcional',
    actividad: 'Hydra (Web Form)',
    completado: false,
    descripcion: 'Ataques de diccionario contra formularios de inicio de sesión HTTP-POST y HTTP-GET.',
  },
  {
    id: 64,
    folio: 'PTECN-WEB-EVAL-29',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Inyección de Código',
    aplicabilidad: 'Opcional',
    actividad: 'SSTI Payloads',
    completado: false,
    descripcion: 'Evaluación de vulnerabilidades de Server-Side Template Injection usando payloads especializados.',
  },
  {
    id: 65,
    folio: 'PTECN-WEB-EVAL-30',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Inyección de Código',
    aplicabilidad: 'Opcional',
    actividad: 'XSS Exploitation',
    completado: false,
    descripcion: 'Inyección y ejecución manual de scripts maliciosos del lado del cliente (Stored/Reflected/DOM XSS).',
  },
  {
    id: 66,
    folio: 'PTECN-WEB-EVAL-31',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Inyección de Código',
    aplicabilidad: 'Opcional',
    actividad: 'CSRF Exploitation',
    completado: false,
    descripcion: 'Pruebas de falsificación de peticiones en sitios cruzados sin tokens de mitigación.',
  },
  {
    id: 67,
    folio: 'PTECN-WEB-EVAL-32',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Ataques de Sesión',
    aplicabilidad: 'Opcional',
    actividad: 'Session Hijacking',
    completado: false,
    descripcion: 'Secuestro y suplantación de sesiones de usuario mediante manipulación de tokens y cabeceras.',
  },
  {
    id: 68,
    folio: 'PTECN-WEB-EVAL-33',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'Pruebas Manuales',
    aplicabilidad: 'Opcional',
    actividad: 'Beef Framework',
    completado: false,
    descripcion: 'Explotación de navegadores cliente mediante inyecciones de scripts de control ofensivo.',
  },
  {
    id: 69,
    folio: 'PTECN-API-EVAL-01',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Enumeración API',
    aplicabilidad: 'Obligatorio',
    actividad: 'Fuzzing de endpoints',
    completado: false,
    descripcion: 'Descubrimiento sistemático de rutas en la API usando wordlists y diccionarios de endpoints.',
  },
  {
    id: 70,
    folio: 'PTECN-API-EVAL-02',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Enumeración API',
    aplicabilidad: 'Obligatorio',
    actividad: 'Validación de requests',
    completado: false,
    descripcion: 'Análisis de los esquemas JSON/XML y los códigos de respuesta del servidor ante peticiones maliciosas.',
  },
  {
    id: 71,
    folio: 'PTECN-API-EVAL-03',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Enumeración API',
    aplicabilidad: 'Obligatorio',
    actividad: 'Fuzzing de parámetros',
    completado: false,
    descripcion: 'Envío sistemático de datos no esperados en parámetros de entrada para buscar excepciones o fallos en el backend.',
  },
  {
    id: 72,
    folio: 'PTECN-API-EVAL-04',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de API',
    aplicabilidad: 'Obligatorio',
    actividad: 'Astra',
    completado: false,
    descripcion: 'Uso de la herramienta de escaneo automatizado Astra para evaluar APIs REST contra OWASP API Top 10.',
  },
  {
    id: 73,
    folio: 'PTECN-API-EVAL-05',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de API',
    aplicabilidad: 'Obligatorio',
    actividad: 'Zaproxy API Scan',
    completado: false,
    descripcion: 'Escaneo automatizado de vulnerabilidades en APIs importando esquemas OpenAPI (Swagger) o GraphQL.',
  },
  {
    id: 74,
    folio: 'PTECN-API-EVAL-06',
    servicio: 'PTECN',
    tipo: 'Web',
    enAlcance: true,
    fase: 'Explotación',
    subFase: 'Análisis de Tokens',
    aplicabilidad: 'Obligatorio',
    actividad: 'JWT_Tool',
    completado: false,
    descripcion: 'Auditoría, manipulación y bypass de tokens JSON Web Tokens (JWT) mediante ataques de clave pública y algoritmos nulos.',
  },

  // ==========================================
  // PTICN - INFRAESTRUCTURA (27 items)
  // ==========================================
  {
    id: 75,
    folio: 'PTICN-INF-EVAL-01',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'DNS Dumpster',
    completado: false,
    descripcion: 'Recopilación de registros DNS históricos, mapeo de hosts y tablas de direccionamiento IP pasivo.',
  },
  {
    id: 76,
    folio: 'PTICN-INF-EVAL-02',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Crt.sh',
    completado: false,
    descripcion: 'Búsqueda pasiva de subdominios y dominios activos mediante logs de transparencia de certificados (CT Logs).',
  },
  {
    id: 77,
    folio: 'PTICN-INF-EVAL-03',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Censys',
    completado: false,
    descripcion: 'Monitoreo de puertos y servicios expuestos en el espacio de direccionamiento IP público mediante Censys.',
  },
  {
    id: 78,
    folio: 'PTICN-INF-EVAL-04',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Shodan',
    completado: false,
    descripcion: 'Búsqueda e identificación pasiva de sistemas de IoT, servidores e infraestructura expuesta a internet.',
  },
  {
    id: 79,
    folio: 'PTICN-INF-EVAL-05',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'SpiderFoot',
    completado: false,
    descripcion: 'Automatización de recolección de OSINT cruzando cientos de fuentes de datos públicas.',
  },
  {
    id: 80,
    folio: 'PTICN-INF-EVAL-06',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'FOCA',
    completado: false,
    descripcion: 'Extracción de metadatos en documentos públicos indexados en la web corporativa.',
  },
  {
    id: 81,
    folio: 'PTICN-INF-EVAL-07',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'theHarvester',
    completado: false,
    descripcion: 'Recopilación de emails, nombres, subdominios y hosts utilizando motores de búsqueda públicos.',
  },
  {
    id: 82,
    folio: 'PTICN-INF-EVAL-08',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Hunter.io',
    completado: false,
    descripcion: 'Búsqueda e identificación de correos electrónicos corporativos e información de contactos.',
  },
  {
    id: 83,
    folio: 'PTICN-INF-EVAL-09',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Subfinder',
    completado: false,
    descripcion: 'Herramienta de descubrimiento rápido de subdominios a través de múltiples APIs de terceros.',
  },
  {
    id: 84,
    folio: 'PTICN-INF-EVAL-10',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Amass',
    completado: false,
    descripcion: 'Mapeo profundo de red y recopilación de nombres de dominios DNS activos y pasivos.',
  },
  {
    id: 85,
    folio: 'PTICN-INF-EVAL-11',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Public Leaks',
    completado: false,
    descripcion: 'Verificación de bases de datos expuestas o filtraciones públicas de credenciales corporativas.',
  },
  {
    id: 86,
    folio: 'PTICN-INF-EVAL-12',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'WHOIS Analysis',
    completado: false,
    descripcion: 'Consulta de registros de propiedad de dominios y bloques de direccionamiento IP.',
  },
  {
    id: 87,
    folio: 'PTICN-INF-EVAL-13',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Google Dorks',
    completado: false,
    descripcion: 'Consultas avanzadas en motores de búsqueda para indexar archivos de configuración expuestos o logins administrativos.',
  },
  {
    id: 88,
    folio: 'PTICN-INF-EVAL-14',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'GitHub Recon',
    completado: false,
    descripcion: 'Auditoría en repositorios públicos de desarrollo para identificar API Keys, passwords o tokens expuestos.',
  },
  {
    id: 89,
    folio: 'PTICN-INF-EVAL-15',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Pasivo (OSINT)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Social Media Recon',
    completado: false,
    descripcion: 'Inteligencia de fuentes abiertas enfocada en perfiles de empleados para recabar tecnologías internas.',
  },
  {
    id: 90,
    folio: 'PTICN-INF-EVAL-16',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nmap (TCP Stealth)',
    completado: false,
    descripcion: 'Escaneo SYN silencioso para determinar puertos abiertos y estados de firewall.',
  },
  {
    id: 91,
    folio: 'PTICN-INF-EVAL-17',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nmap (UDP Scan)',
    completado: false,
    descripcion: 'Escaneo sistemático de puertos UDP comunes para mapear servicios de DNS, SNMP y DHCP.',
  },
  {
    id: 92,
    folio: 'PTICN-INF-EVAL-18',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Banner Grabbing',
    completado: false,
    descripcion: 'Lectura de los banners iniciales de respuesta de servicios abiertos para inferir software y versiones.',
  },
  {
    id: 93,
    folio: 'PTICN-INF-EVAL-19',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nmap (Host Discovery)',
    completado: false,
    descripcion: 'Ping sweep para enumerar de manera rápida las máquinas vivas en el rango externo.',
  },
  {
    id: 94,
    folio: 'PTICN-INF-EVAL-20',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'DNS-Brute',
    completado: false,
    descripcion: 'Resolución de subdominios utilizando diccionarios agresivos y multihilo.',
  },
  {
    id: 95,
    folio: 'PTICN-INF-EVAL-21',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Zone Transfer (AXFR)',
    completado: false,
    descripcion: 'Intentos de transferencia de zona DNS no autorizada para volcar el árbol completo de hosts.',
  },
  {
    id: 96,
    folio: 'PTICN-INF-EVAL-22',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Reconocimiento',
    subFase: 'Activo (Enumeración)',
    aplicabilidad: 'Obligatorio',
    actividad: 'Reverse DNS',
    completado: false,
    descripcion: 'Mapeo inverso de registros PTR para buscar nombres de host válidos asociados a IPs.',
  },
  {
    id: 97,
    folio: 'PTICN-INF-EVAL-23',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis Automatizado',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nessus Professional Scan',
    completado: false,
    descripcion: 'Evaluación integral de vulnerabilidades del segmento con firmas actualizadas Nessus.',
  },
  {
    id: 98,
    folio: 'PTICN-INF-EVAL-24',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Configuración',
    aplicabilidad: 'Obligatorio',
    actividad: 'ScoutSuite',
    completado: false,
    descripcion: 'Auditoría de seguridad en la configuración de APIs de nubes públicas (AWS/GCP/Azure).',
  },
  {
    id: 99,
    folio: 'PTICN-INF-EVAL-25',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Escaneo Externo',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nessus External',
    completado: false,
    descripcion: 'Escaneo de vulnerabilidades desde una perspectiva perimetral expuesta a internet.',
  },
  {
    id: 100,
    folio: 'PTICN-INF-EVAL-26',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Explotación',
    subFase: 'Password Spraying',
    aplicabilidad: 'Obligatorio',
    actividad: 'Burp Intruder',
    completado: false,
    descripcion: 'Ataques de rociado de contraseñas débiles contra portales SSO, VPN o servicios web expuestos.',
  },
  {
    id: 101,
    folio: 'PTICN-INF-EVAL-27',
    servicio: 'PTICN',
    tipo: 'Infraestructura',
    enAlcance: true,
    fase: 'Explotación',
    subFase: 'Password Spraying',
    aplicabilidad: 'Obligatorio',
    actividad: 'MSOLSpray',
    completado: false,
    descripcion: 'Rociado de contraseñas en infraestructuras de login de Office365 / Entra ID.',
  },

  // ==========================================
  // PTICN-VPN - INFRAESTRUCTURA (31 items)
  // ==========================================
  {
    id: 102,
    folio: 'PTICN-VPN-EVAL-01',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Escaneo de VPN',
    aplicabilidad: 'Obligatorio',
    actividad: 'IKE-Scan',
    completado: false,
    descripcion: 'Descubrimiento de gateways IPSec VPN e identificación de algoritmos criptográficos débiles en Fase 1.',
  },
  {
    id: 103,
    folio: 'PTICN-VPN-EVAL-02',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'Análisis de Protocolos',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nmap (VPN Scripts)',
    completado: false,
    descripcion: 'Escaneo para detectar y perfilar túneles OpenVPN, PPTP o AnyConnect.',
  },
  {
    id: 104,
    folio: 'PTICN-VPN-EVAL-03',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'DISCOVERY',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nmap (TCP Ping / ICMP)',
    completado: false,
    descripcion: 'Descubrimiento de hosts encendidos dentro del tunel VPN.',
  },
  {
    id: 105,
    folio: 'PTICN-VPN-EVAL-04',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Reconocimiento',
    subFase: 'DISCOVERY',
    aplicabilidad: 'Obligatorio',
    actividad: 'Advanced IP Scanner',
    completado: false,
    descripcion: 'Mapeo rápido de direccionamiento IP y resolución de nombres NetBIOS.',
  },
  {
    id: 106,
    folio: 'PTICN-VPN-EVAL-05',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'VULN',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nessus Professional',
    completado: false,
    descripcion: 'Escaneo interno de la red corporativa alcanzada a través de la VPN.',
  },
  {
    id: 107,
    folio: 'PTICN-VPN-EVAL-06',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'VULN',
    aplicabilidad: 'Obligatorio',
    actividad: 'Acunetix',
    completado: false,
    descripcion: 'Escaneo DAST de las consolas de administración expuestas en el túnel.',
  },
  {
    id: 108,
    folio: 'PTICN-VPN-EVAL-07',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'SNMP',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de SNMP',
    completado: false,
    descripcion: 'Extracción de tablas ARP e información de red a través de OIDs públicos.',
  },
  {
    id: 109,
    folio: 'PTICN-VPN-EVAL-08',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'RPC',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de RPC',
    completado: false,
    descripcion: 'Consulta a rpcdump para identificar interfaces IPC y accesos sin autenticar.',
  },
  {
    id: 110,
    folio: 'PTICN-VPN-EVAL-09',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'LDAP',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de LDAP',
    completado: false,
    descripcion: 'Extracción de dominios LDAP, nombres de computadoras y políticas.',
  },
  {
    id: 111,
    folio: 'PTICN-VPN-EVAL-10',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'SMB',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de SMB',
    completado: false,
    descripcion: 'Validación de vulnerabilidad de SMB Signing y recursos compartidos públicos.',
  },
  {
    id: 112,
    folio: 'PTICN-VPN-EVAL-11',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'RDP',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de RDP',
    completado: false,
    descripcion: 'Validación de soporte de NLA y vulnerabilidades en terminales RDP.',
  },
  {
    id: 113,
    folio: 'PTICN-VPN-EVAL-12',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'SSH',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de SSH',
    completado: false,
    descripcion: 'Auditoría de llaves criptográficas y algoritmos de intercambio en SSH.',
  },
  {
    id: 114,
    folio: 'PTICN-VPN-EVAL-13',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'HTTP HTTPS',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración Web',
    completado: false,
    descripcion: 'Búsqueda de sistemas heredados, portales de administración y APIs dentro de la red.',
  },
  {
    id: 115,
    folio: 'PTICN-VPN-EVAL-14',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'AD AUDIT',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de AD',
    completado: false,
    descripcion: 'Mapeo de la estructura del Active Directory desde un host interno.',
  },
  {
    id: 116,
    folio: 'PTICN-VPN-EVAL-15',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'TOMCAT JAVA RMI JDWP',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de servicios Java',
    completado: false,
    descripcion: 'Validación de seguridad en aplicaciones empresariales corriendo consolas Tomcat o JMX.',
  },
  {
    id: 117,
    folio: 'PTICN-VPN-EVAL-16',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'SQL DBS',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de MSSQL',
    completado: false,
    descripcion: 'Detección de instancias SQL Server e identificación de puertos dinámicos.',
  },
  {
    id: 118,
    folio: 'PTICN-VPN-EVAL-17',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'ORACLE',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de Oracle',
    completado: false,
    descripcion: 'Búsqueda e identificación de SIDs de bases de datos Oracle activas.',
  },
  {
    id: 119,
    folio: 'PTICN-VPN-EVAL-18',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'FTP TELNET',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de servicios Cleartext',
    completado: false,
    descripcion: 'Búsqueda e identificación de logins en texto claro (FTP, Telnet).',
  },
  {
    id: 120,
    folio: 'PTICN-VPN-EVAL-19',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'NFS',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de NFS',
    completado: false,
    descripcion: 'Comprobación de unidades NFS compartidas públicamente o mal configuradas.',
  },
  {
    id: 121,
    folio: 'PTICN-VPN-EVAL-20',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'VNC',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de VNC',
    completado: false,
    descripcion: 'Búsqueda de escritorios remotos compartidos sin autenticación o con claves por defecto.',
  },
  {
    id: 122,
    folio: 'PTICN-VPN-EVAL-21',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Enumeración',
    subFase: 'IMAP',
    aplicabilidad: 'Obligatorio',
    actividad: 'Enumeración de correo',
    completado: false,
    descripcion: 'Mapeo de servidores internos de correo y protocolos SMTP/IMAP/POP3.',
  },
  {
    id: 123,
    folio: 'PTICN-VPN-EVAL-22',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Detección de Vulnerabilidades',
    subFase: 'MANUAL',
    aplicabilidad: 'Obligatorio',
    actividad: 'MANUAL',
    completado: false,
    descripcion: 'Auditoría ofensiva manual en servicios locales identificados.',
  },
  {
    id: 124,
    folio: 'PTICN-VPN-EVAL-23',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'CVE EXPLOTABLES',
    aplicabilidad: 'Obligatorio',
    actividad: 'Explotación de vulnerabilidades conocidas',
    completado: false,
    descripcion: 'Ataques específicos contra fallos documentados y con exploits públicos.',
  },
  {
    id: 125,
    folio: 'PTICN-VPN-EVAL-24',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'LATERAL',
    aplicabilidad: 'Obligatorio',
    actividad: 'Impacket (ntlmrelayx)',
    completado: false,
    descripcion: 'Ataques de retransmisión de hashes NTLM (NTLM Relay) para comprometer hosts remotos.',
  },
  {
    id: 126,
    folio: 'PTICN-VPN-EVAL-25',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'KERBEROS',
    aplicabilidad: 'Obligatorio',
    actividad: 'Rubeus',
    completado: false,
    descripcion: 'Abuso y manipulación del protocolo Kerberos en Active Directory (AS-REP Roasting, Kerberoasting).',
  },
  {
    id: 127,
    folio: 'PTICN-VPN-EVAL-26',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'KERBEROS',
    aplicabilidad: 'Obligatorio',
    actividad: 'Impacket (GetNPUsers)',
    completado: false,
    descripcion: 'Extracción de hashes Kerberos para cuentas sin pre-autenticación requerida.',
  },
  {
    id: 128,
    folio: 'PTICN-VPN-EVAL-27',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Explotación',
    subFase: 'PRIVESC',
    aplicabilidad: 'Obligatorio',
    actividad: 'PowerUp',
    completado: false,
    descripcion: 'Auditoría automática de privilegios en equipos Windows usando scripts de PowerShell.',
  },
  {
    id: 129,
    folio: 'PTICN-VPN-EVAL-28',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Post-Explotación',
    subFase: 'EXPLORATION',
    aplicabilidad: 'Obligatorio',
    actividad: 'Wireshark',
    completado: false,
    descripcion: 'Captura y sniffing de tramas de red locales para análisis posterior.',
  },
  {
    id: 130,
    folio: 'PTICN-VPN-EVAL-29',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Post-Explotación',
    subFase: 'EXPLORATION',
    aplicabilidad: 'Obligatorio',
    actividad: 'Nmap (POS Scan)',
    completado: false,
    descripcion: 'Escaneo y perfilamiento de terminales de punto de venta (POS) activos.',
  },
  {
    id: 131,
    folio: 'PTICN-VPN-EVAL-30',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Post-Explotación',
    subFase: 'PERSISTENCE',
    aplicabilidad: 'Obligatorio',
    actividad: 'PowerView',
    completado: false,
    descripcion: 'Mapeo detallado de relaciones de confianza en Active Directory.',
  },
  {
    id: 132,
    folio: 'PTICN-VPN-EVAL-31',
    servicio: 'PTICN-VPN',
    tipo: 'Infraestructura',
    enAlcance: false,
    fase: 'Post-Explotación',
    subFase: 'EXFILTRATION',
    aplicabilidad: 'Obligatorio',
    actividad: 'Iodine',
    completado: false,
    descripcion: 'Exfiltración de datos encapsulando tráfico de red completo sobre tramas DNS (DNS Tunneling).',
  },
];
