services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: katana
      POSTGRES_PASSWORD: 299792458.Light
      POSTGRES_DB: katana_security_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
